# Generated by Django 4.2.5 on 2023-09-06 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_collection', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('date_rdv', models.DateField()),
                ('objet', models.CharField(max_length=250)),
                ('confirme', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_modele', models.IntegerField(default=0)),
                ('nom_modele', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=10)),
                ('taille', models.CharField(max_length=5)),
                ('modele', models.ImageField(upload_to='media')),
                ('modele1', models.ImageField(upload_to='media')),
                ('modele2', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('prix', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Commandemodele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('reception', models.CharField(max_length=30)),
                ('paiement', models.CharField(max_length=30)),
                ('confirme', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.modele')),
            ],
        ),
        migrations.CreateModel(
            name='Commandeaccessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('reception', models.CharField(max_length=30)),
                ('paiement', models.CharField(max_length=30)),
                ('confirme', models.BooleanField(default=False)),
                ('accessoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.collection')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Accessoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_accessoire', models.IntegerField(default=0)),
                ('nom_accessoire', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=5)),
                ('modele', models.ImageField(upload_to='media')),
                ('modele1', models.ImageField(upload_to='media')),
                ('modele2', models.ImageField(upload_to='media')),
                ('description', models.CharField(max_length=250)),
                ('prix', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.collection')),
            ],
        ),
    ]
