# Generated by Django 4.2.5 on 2023-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_collection_rdv_modele_commandemodele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeaccessoire',
            name='paiement',
        ),
        migrations.RemoveField(
            model_name='commandemodele',
            name='paiement',
        ),
        migrations.AddField(
            model_name='commandemodele',
            name='taille',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
