# Generated by Django 4.2.5 on 2023-10-10 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_remove_commandeaccessoire_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeaccessoire',
            name='accessoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.accessoire'),
        ),
    ]
